#!/bin/bash

if host ya.ru > /dev/null 2>&1; then
    echo "DNS resolve works fine"
else 
    echo "DNS resolve is unavailable"
fi

if ping -c 4 8.8.8.8 > /dev/null 2>&1; then
    echo "Network connection is available"
else 
    echo "Network connection is unavailable"
    exit 1
fi

ping vk.com -q -c 4 | tail -3
